### ISSUE TITLE
feature/create-banner-component

### ISSUE THREAD

**Issue by reyesjl** [reyesjl/firstfivecloud#24]
## Description
Create a banner component that can be re-used across all service pages that have a banner.

## Requirements
- [ ] Must contain attribute for title
- [ ] Must contain attribute for a background image
- [ ] Must contain the service button's text
- [ ] Must contain the service buttons link

## Usage
I want to be able to use the component as show in the example below:

`
  {% include 'your_app/components/banner_component.html' with
      banner_image_url='path/to/your/image.jpg'
      banner_title='Your Banner Title'
      button_url='your/button/url/'
      button_text='Button Text'
  %}
`

**Comment by Bennm23** [comment]
U can do it

**Comment by reyesjl** [comment]
Actually i did everything following the docs, and my shits still broken. Might need some help on this later, seems like a simple concept, so I am not sure why it does not work.
